
import React from 'react';

export const BRAND_INFO = {
  name: 'Manage Money',
  developer: 'Graphico Global',
  website: 'https://www.graphicoglobal.com',
  facebook: 'https://www.facebook.com/graphicoglobal',
  whatsapp: 'https://wa.me/8801930277399',
  email: 'mailto:graphicoglobal@gmail.com',
  telegram: 'https://t.me/GraphicoGlobal',
};

export const THEME_COLORS = [
  { name: 'Royal Blue', color: '#4169E1' },
  { name: 'Forest Green', color: '#228B22' },
  { name: 'Normal Green', color: '#008000' },
  { name: 'Sky Blue', color: '#87CEEB' },
  { name: 'Maroon', color: '#800000' },
  { name: 'Pink', color: '#FF69B4' },
  { name: 'Golden', color: '#FFD700' },
];

export const CURRENCIES = [
  { code: '৳', name: 'BDT' },
  { code: '$', name: 'USD' },
  { code: '€', name: 'EUR' },
  { code: '£', name: 'GBP' },
  { code: '₹', name: 'INR' },
  { code: '¥', name: 'JPY' },
  { code: 'SR', name: 'SAR' },
  { code: 'AED', name: 'AED' },
  { code: 'RM', name: 'MYR' },
  { code: 'S$', name: 'SGD' },
];

export const TRANSLATIONS = {
  EN: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    reports: 'Reports',
    settings: 'Settings',
    productStock: 'Product Stock',
    productSale: 'Product Sale',
    partners: 'Partners',
    income: 'Income',
    expense: 'Expense',
    dues: 'Dues',
    totalBalance: 'Total Balance',
    addTransaction: 'Add Record',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    history: 'Transaction History',
    search: 'Search Records...',
    filterDate: 'Filter Date',
    exportPDF: 'Download PDF',
    exportExcel: 'Download Excel',
    language: 'Language',
    theme: 'Theme',
    profile: 'Profile Preferences',
    logout: 'Logout',
    resetApp: 'Reset System',
    secretCode: 'Secret Code',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    login: 'Login',
    signup: 'Create Account',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    welcome: 'Welcome',
    save: 'Save Changes',
    cancel: 'Cancel',
    summary: 'Summary',
    noTransactions: 'No records found.',
    facebook: 'Facebook',
    whatsappSupport: 'WhatsApp',
    mobileNumber: 'Mobile Number',
    calculator: 'Calculator',
    printInvoice: 'Invoice Preview',
    currency: 'Currency',
    showPassword: 'View Password',
    enterSecret: 'Enter Secret Code to Reveal',
    verify: 'Verify Now',
    todaysSummary: "Today's Summary",
    quickEntry: 'Add New Record',
    accountRecovery: 'Account Recovery',
    secretTooltip: 'This code is needed to reset password if forgotten.',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update Record',
    print: 'Print Now',
    close: 'Close',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    newPassword: 'New Password',
    recoverySuccess: 'Password recovered successfully!',
    recoveryError: 'Invalid Email or Secret Code',
    themeColor: 'App Theme Color',
    switchAccount: 'Switch Account',
    role: 'Select Role',
    admin: 'Admin',
    moderator: 'Moderator',
    moderatorSettings: 'Moderator Access Settings',
    moderatorEmail: 'Moderator Email',
    moderatorCode: 'Moderator User Code',
    insufficientPermissions: 'You do not have permission to delete records.',
    resetSecurityTitle: 'Confirm System Reset',
    enterAdminSecret: 'Enter Admin Secret Code to confirm reset',
    productName: 'Product Name',
    productCode: 'Product Code',
    buyPrice: 'Buy Price',
    sellPrice: 'Sell Price',
    partnerName: 'Partner Name',
    partnerMobile: 'Mobile Number',
    partnerDesc: 'Identity/Short Description',
    backupRestore: 'Data Backup & Restore',
    exportData: 'Export Shop Data',
    importData: 'Import Shop Data',
    themeMode: 'Theme Mode',
    auto: 'System Default',
    customerName: 'Customer Name',
    invoiceId: 'Invoice ID',
    addItem: 'Add Item',
    finishSale: 'Finish Sale',
    qty: 'Qty',
    price: 'Price',
    total: 'Total'
  },
  BN: {
    dashboard: 'ড্যাশবোর্ড',
    transactions: 'লেনদেন',
    reports: 'রিপোর্ট',
    settings: 'সেটিংস',
    productStock: 'প্রোডাক্ট স্টক',
    productSale: 'পণ্য বিক্রয়',
    partners: 'পার্টনার লিস্ট',
    income: 'আয়',
    expense: 'ব্যয়',
    dues: 'বাকি (দেনা)',
    totalBalance: 'মোট ব্যালেন্স',
    addTransaction: 'হিসাব যুক্ত করুন',
    description: 'বিবরণ লিখুন',
    amount: 'টাকার পরিমাণ',
    date: 'তারিখ',
    category: 'খাত/বিভাগ',
    history: 'লেনদেনের ইতিহাস',
    search: 'হিসাব খুঁজুন...',
    filterDate: 'তারিখ ফিল্টার',
    exportPDF: 'পিডিএফ ডাউনলোড',
    exportExcel: 'এক্সেল ডাউনলোড',
    language: 'ভাষা',
    theme: 'থিম',
    profile: 'প্রোফাইল সেটিংস',
    logout: 'লগ আউট',
    resetApp: 'সিস্টেম রিসেট',
    secretCode: 'সিক্রেট কোড',
    password: 'পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    login: 'লগইন',
    signup: 'অ্যাকাউন্ট তৈরি করুন',
    daily: 'দৈনিক',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    yearly: 'বার্ষিক',
    welcome: 'স্বাগতম',
    save: 'পরিবর্তন সংরক্ষণ করুন',
    cancel: 'বাতিল',
    summary: 'সারসংক্ষেপ',
    noTransactions: 'কোনো লেনদেন পাওয়া যায়নি।',
    facebook: 'ফেসবুক',
    whatsappSupport: 'হোয়াটসঅ্যাপ',
    mobileNumber: 'মোবাইল নম্বর',
    calculator: 'ক্যালকুলেটর',
    printInvoice: 'ইনভয়েস প্রিভিউ',
    currency: 'কারেন্সি',
    showPassword: 'পাসওয়ার্ড দেখুন',
    enterSecret: 'দেখার জন্য সিক্রেট কোড দিন',
    verify: 'যাচাই করুন',
    todaysSummary: 'আজকের হিসাব',
    quickEntry: 'নতুন হিসাব যুক্ত করুন',
    accountRecovery: 'অ্যাকাউন্ট রিকভারি',
    secretTooltip: 'পাসওয়ার্ড ভুলে গেলে পুনরুদ্ধারের জন্য এই কোডটি প্রয়োজন।',
    edit: 'এডিট',
    delete: 'ডিলিট',
    update: 'হিসাব আপডেট',
    print: 'প্রিন্ট করুন',
    close: 'বন্ধ করুন',
    resetPassword: 'পাসওয়ার্ড রিসেট',
    backToLogin: 'লগইন এ ফিরে যান',
    newPassword: 'নতুন পাসওয়ার্ড',
    recoverySuccess: 'পাসওয়ার্ড সফলভাবে পুনরুদ্ধার করা হয়েছে!',
    recoveryError: 'ভুল ইমেইল অথবা সিক্রেট কোড',
    themeColor: 'অ্যাপ থিম কালার',
    switchAccount: 'অ্যাকাউন্ট সুইচ',
    role: 'রোল সিলেক্ট করুন',
    admin: 'এডমিন',
    moderator: 'মডারেটর',
    moderatorSettings: 'মডারেটর এক্সেস সেটিংস',
    moderatorEmail: 'মডারেটর ইমেইল',
    moderatorCode: 'মডারেটর ইউজার কোড',
    insufficientPermissions: 'আপনার এই লেনদেনটি ডিলিট করার অনুমতি নেই।',
    resetSecurityTitle: 'সিস্টেম রিসেট নিশ্চিত করুন',
    enterAdminSecret: 'রিসেট করতে এডমিন সিক্রেট কোড দিন',
    productName: 'পণ্যের নাম',
    productCode: 'প্রোডাক্ট কোড',
    buyPrice: 'ক্রয় মূল্য',
    sellPrice: 'বিক্রয় মূল্য',
    partnerName: 'পার্টনারের নাম',
    partnerMobile: 'মোবাইল নম্বর',
    partnerDesc: 'পরিচয়/ছোট বিবরণ',
    backupRestore: 'ডাটা ব্যাকআপ ও রিস্টোর',
    exportData: 'সব ডাটা ডাউনলোড করুন',
    importData: 'ডাটা ফাইল আপলোড করুন',
    themeMode: 'থিম মুড',
    auto: 'ডিভাইস সেটিংস',
    customerName: 'কাস্টমারের নাম',
    invoiceId: 'ইনভয়েস আইডি',
    addItem: 'পণ্য যোগ করুন',
    finishSale: 'বিক্রয় সম্পন্ন করুন',
    qty: 'পরিমাণ',
    price: 'মূল্য',
    total: 'মোট'
  }
};
